# Generated by Django 6.1 on 2026-08-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
